CREATE TABLE IF NOT EXISTS league_to_scan (
    id      BIGSERIAL PRIMARY KEY,
    league  VARCHAR(300) NOT NULL
);

DROP TABLE IF EXISTS league_to_scan CASCADE;
INSERT INTO league_to_scan (id, league)
VALUES (default, 'Ставки на фактический исход'),
       (default, 'Algeria Professional Ligue 1'),
       (default, 'Argentina Superliga'),
       (default, 'AUSTRIA BUNDESLIGA'),
       (default, 'Australia Hyundai A League'),
       (default, 'Austria 2nd Liga'),
       (default, 'BELGIUM FIRST DIVISION A'),
       (default, 'Belgium First Division B'),
       (default, 'Bolivia Professional Football League'),
       (default, 'Chile Primera Division'),
       (default, 'Colombia Primera A'),
       (default, 'Colombia Primera B'),
       (default, 'Costa Rica Campeonato Primera Division'),
       (default, 'Croatia Prva Liga'),
       (default, 'Czech Republic First League'),
       (default, 'DENMARK SUPER LEAGUE'),
       (default, 'Egypt Premier League'),
       (default, 'ENGLISH PREMIER LEAGUE'),
       (default, 'ENGLISH CHAMPIONSHIP'),
       (default, 'FRANCE DOMINO''S LIGUE 2'),
       (default, 'FRANCE LIGUE 1'),
       (default, 'GERMANY BUNDESLIGA'),
       (default, 'GERMANY BUNDESLIGA 2'),
       (default, 'Greece Super League'),
       (default, 'Greece Super League 2'),
       (default, 'Guatemala Liga National'),
       (default, 'Hungary OTP Bank Liga NB 1'),
       (default, 'India I-League'),
       (default, 'India Super League'),
       (default, 'Iran Pro League'),
       (default, 'Israel Liga Leumit'),
       (default, 'Israel Premier League'),
       (default, 'ITALY SERIE A'),
       (default, 'ITALY SERIE B'),
       (default, 'Jamaica Premier League'),
       (default, 'Kenya Premier League'),
       (default, 'Kuwait Premier League'),
       (default, 'Mexico Liga de Ascenso'),
       (default, 'Mexico Primera Division'),
       (default, 'Morocco Botola Pro'),
       (default, 'NETHERLANDS EREDIVISIE'),
       (default, 'Netherlands Eerste Divisie'),
       (default, 'Northern Ireland Danske Bank Premiership'),
       (default, 'Oman Professional League'),
       (default, 'Paraguay Primera Division'),
       (default, 'Peru Liga 1'),
       (default, 'PORTUGAL LIGA NOS'),
       (default, 'Poland Ekstraklasa'),
       (default, 'Portugal Ledman LigaPro'),
       (default, 'Romania Liga 1'),
       (default, 'Russia Premier League'),
       (default, 'Saudi Arabia Pro League'),
       (default, 'SCOTLAND PREMIERSHIP'),
       (default, 'Scotland Championship'),
       (default, 'South Africa ABSA Premiership'),
       (default, 'SPAIN LA LIGA'),
       (default, 'SPAIN LA LIGA 2'),
       (default, 'SWISS RAIFFEISEN SUPER LEAGUE'),
       (default, 'Swiss Challenge League'),
       (default, 'Tunisia Professional Ligue 1'),
       (default, 'TURKEY SUPER LEAGUE'),
       (default, 'Turkey 1st Lig'),
       (default, 'UAE Arabian Gulf League'),
       (default, 'Venezuela Primera Division'),
       (default, 'Qatar QNB Stars League');

